[package]
name = "soroban-security-rules-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.90", features = ["full"] }
proc-macro2 = { version = "1.0.92", features = ["span-locations"] }
thiserror = "2.0.8"
macro_lib = { path = "macro_lib" }
serde = "1.0.216"

[dev-dependencies]
soroban-sdk = "22.0.4"

[workspace]
members = [".", "./macro_lib"]
