[package]
name = "soroban-security-rules-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.95", features = ["full"] }
quote = "1.0.38"
proc-macro2 = { version = "1.0.92", features = ["span-locations"] }
thiserror = "2.0.9"
macro_lib = { path = "macro_lib" }
serde = "1.0.217"
serde_json = "1.0.134"
uuid = { version = "1.1", features = ["v4"] }

[dev-dependencies]
soroban-sdk = "22.0.4"

[workspace]
members = [".", "macro_lib", "rules", "soroban_rules_runner"]
