[package]
name = "soroban-security-rules-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.87", features = ["full"] }
proc-macro2 = { version = "1.0.89", features = ["span-locations"] }
thiserror = "1.0.68"
macro_lib = { path = "macro_lib" }

[dev-dependencies]
soroban-sdk = "21.7.6"

workspace = { members = [".", "./macro_lib"] }
