name: Artifacts

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    defaults:
      run:
        working-directory: .

    steps:
      - name: Setup Rust
        uses: actions/checkout@v4.1.3
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Update Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install clippy nightly
        run: rustup component add clippy-preview
      - name: Build Release
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: target/x86_64-unknown-linux-gnu/release/
